package app.efficientbytes.booleanbear.utils

const val BASE_URL = "https://booleanbear-fb7pgif5zq-uc.a.run.app"
const val DATABASE_NAME = "APP_DATABASE"
const val DUMMY_TABLE = "dummy"
const val USER_PROFILE_TABLE = "user_profile"
const val USER_PROFILE_DOCUMENT_PATH = "/USER/PRIVATE_PROFILE/FILES/"
const val SINGLE_DEVICE_LOGIN_TABLE = "single_device_login"
const val SINGLE_DEVICE_LOGIN_DOCUMENT_PATH = "/SINGLE_DEVICE_LOGIN/"
const val PROFESSION_ADAPTER_TABLE = "professions"
const val ISSUE_CATEGORY_ADAPTER_TABLE = "issue_categories"
const val SHUFFLED_CATEGORY_TABLE = "shuffled_categories"
const val CATEGORY_CONTENT_ID_TABLE = "category_content_ids"
const val AUTH_CUSTOM_COROUTINE_SCOPE = "auth-scope"
const val USER_SCREEN_TIMING_TABLE = "user_screen_timing"
const val LOCAL_SHUFFLED_YOUTUBE_CONTENT_VIEW_TABLE = "local_shuffled_youtube_content_view"
const val REMOTE_SHUFFLED_YOUTUBE_CONTENT_VIEW_TABLE = "remote_shuffled_youtube_content_view"
const val INSTRUCTOR_PROFILE_TABLE = "instructor_profile"
const val MENTIONED_LINKS_TABLE = "mentioned_links"
const val HOME_PAGE_BANNER_AD_TABLE = "home_page_banner_ad"
const val FCM_TOKEN_TABLE = "fcm_token"
const val ID_TOKEN_TABLE = "id_token"